apiVersion: v1
kind: ConfigMap
metadata:
  name: shipping
  namespace: roboshop
data:
  CART_ENDPOINT: "cart:8080"
  DB_HOST: "mysql"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shipping
  namespace: roboshop
  # these are replica set labels
  labels:
    component: shipping
    project: roboshop
    tier: backend
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      component: shipping
      project: roboshop
      tier: backend
  # pod definition
  template:
    metadata:
      labels:
        component: shipping
        project: roboshop
        tier: backend
    spec:
      containers:
      - name: shipping
        image: eshwarkodavali/shipping:v1
        envFrom:
        - configMapRef:
            name: shipping
        ports:
        - name: liveness-port
          containerPort: 8080
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health # Or your specific readiness check endpoint
            port: liveness-port
          periodSeconds: 15 # How often to perform the probe
          failureThreshold: 1 # Number of consecutive failures before marking as unready
        livenessProbe:
          httpGet:
            path: /health # Or your specific readiness check endpoint
            port: liveness-port
          periodSeconds: 15 # How often to perform the probe
          failureThreshold: 1 # Number of consecutive failures before marking as unready
---
apiVersion: v1
kind: Service
metadata:
  name: shipping
  namespace: roboshop
spec:
  selector:
    component: shipping
    project: roboshop
    tier: backend
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port