apiVersion: v1
kind: ConfigMap
metadata:
  name: user
  namespace: roboshop
data: 
  REDIS_URL: "redis://redis:6379"
  MONGO_URL: "mongodb://mongodb:27017/users"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user
  namespace: roboshop
  # these are replica set labels
  labels:
    component: user
    project: roboshop
    tier: backend
spec:
  replicas: 1
  selector:
    # these labels are used to select pods
    matchLabels:
      component: user
      project: roboshop
      tier: backend
  # pod definition
  template:
    metadata:
      labels:
        component: user
        project: roboshop
        tier: backend
    spec:
      containers:
      - name: user
        image: eshwarkodavali/user:v1
        envFrom:
        - configMapRef:
            name: user
        ports:
        - name: liveness-port
          containerPort: 8080
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /health # Or your specific readiness check endpoint
            port: liveness-port
          periodSeconds: 15 # How often to perform the probe
          failureThreshold: 1 # Number of consecutive failures before marking as unready
        livenessProbe:
          httpGet:
            path: /health # Or your specific readiness check endpoint
            port: liveness-port
          periodSeconds: 15 # How often to perform the probe
          failureThreshold: 1 # Number of consecutive failures before marking as unready
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: roboshop
spec:
  selector:
    component: user
    project: roboshop
    tier: backend
  ports:
    - protocol: TCP
      port: 8080 # service port
      targetPort: 8080 # container port